// <auto-generated/>
using Cockpit.Features;
using Cockpit.Models;
using Cockpit.Services;

namespace Cockpit.Components;

public partial class PermissionSettings
{
	readonly GlobalPermissionFeature _globalPermissionFeature;
	private List<string> _commands = [];
	private bool _showAddDialog;
	private string _newCommand = string.Empty;

	public PermissionSettings(GlobalPermissionFeature globalPermissionFeature)
	{
		_globalPermissionFeature = globalPermissionFeature;
	}

	protected override void OnInitialized()
	{
		LoadPermissions();
		_globalPermissionFeature.OnPermissionsChanged += LoadPermissions;
	}

	private void LoadPermissions()
	{
		_commands = [.. _globalPermissionFeature.GetAll()];
		StateHasChanged();
	}

	private void ShowAddDialog()
	{
		_showAddDialog = true;
		_newCommand = string.Empty;
	}

	private void HideAddDialog()
	{
		_showAddDialog = false;
	}

	private void AddPermission()
	{
		if(string.IsNullOrWhiteSpace(_newCommand))
		{
			return;
		}

		_globalPermissionFeature.Add(_newCommand);

		HideAddDialog();
	}

	private void RemovePermission(string command)
	{
		_globalPermissionFeature.Remove(command);
	}

	public void Dispose()
	{
		_globalPermissionFeature.OnPermissionsChanged -= LoadPermissions;
	}
}