// <auto-generated/>
using Cockpit.Models;
using Cockpit.Services;

namespace Cockpit.Components;

public partial class PermissionSettings
{
	private List<ToolPermission> _allowedPermissions = [];
	private bool _showAddDialog;
	private string _newPattern = string.Empty;
	private PatternType _newPatternType = PatternType.Exact;

	protected override void OnInitialized()
	{
		LoadPermissions();
		PermissionService.OnPermissionsChanged += LoadPermissions;
	}

	private void LoadPermissions()
	{
		List<ToolPermission> allPermissions = PermissionService.GetGlobalPermissions();
		_allowedPermissions = allPermissions.Where(p => p.IsAllowed).ToList();
		StateHasChanged();
	}

	private void ShowAddDialog()
	{
		_showAddDialog = true;
		_newPattern = string.Empty;
		_newPatternType = PatternType.Exact;
	}

	private void HideAddDialog()
	{
		_showAddDialog = false;
	}

	private void AddPermission()
	{
		if(string.IsNullOrWhiteSpace(_newPattern))
		{
			return;
		}

		ToolPermission permission = new()
		{
			Pattern = _newPattern.Trim(),
			Type = _newPatternType,
			IsAllowed = true,
			Scope = PermissionScope.Global
		};

		PermissionService.AddGlobalPermission(permission);
		HideAddDialog();
	}

	private void RemovePermission(ToolPermission permission)
	{
		PermissionService.RemoveGlobalPermission(permission);
	}

	public void Dispose()
	{
		PermissionService.OnPermissionsChanged -= LoadPermissions;
	}
}